plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
   // add(sourceSets.main, "${mod_id}.refmap.json")

  //  config("${mod_id}.mixins.json")
   // config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = false

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    compileOnly project(":common")
   // annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly group: 'org.jetbrains',name:'annotations',version: '24.1.0'

    modImplementation "curse.maven:little-logistics-570050:4799459"
    //cooked
    //modImplementation("dev.murad.littlelogistics:littlelogistics:${ll_version}")
    modCompileOnly("com.jozufozu.flywheel:${flywheel_version}")

    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }

    modCompileOnly("com.tterrag.registrate:Registrate:${registrate_version}")

    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
}

jar {
    finalizedBy('reobfJar')
   // manifest.attributes([
   //         "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
   // ])
}
